### ISSUE TITLE
Multilayout Support

### ISSUE THREAD

**Issue by luis-godinez** [zykrah/firmware-scripts#10]
I had some challenges creating a multilayout keyboard with 2+ options available for the bottom row. I have had success in a separate project but I eventually found the problem after much trial and error. It appears that that at least one of the multilayout options **MUST** contain all the possible row & column combinations. You see, some of the multilayout options may be omitting certain keys due to changes in layout and key width.

In the end, I had to create a false row (multilayout index 4) that doesn't exist on my keyboard but does incorporate all the possible row/cols for the multilayout option. You can reproduce this behavior by deleting this multilayout option and running your script. If you look at the `kb.h` file, you'll see duplicate entries like `k3<letter>`. This duplicate entries in the layout will cause QMK to throw the following error when compiling: `duplicate macro parameter`

<img width="1033" alt="Screenshot 2024-04-21 at 7 18 57 PM" src="https://github.com/zykrah/firmware-scripts/assets/9256751/f94ce8c7-654d-4f6b-93a0-f19632835f75">

<img width="748" alt="image" src="https://github.com/zykrah/firmware-scripts/assets/9256751/e3dcd7b4-6871-416b-ae16-723e11b8b37e">

KLE:
http://www.keyboard-layout-editor.com/#/gists/ef9bd1634f1c1bfedb62161b83bae417
[priya50 (13).json](https://github.com/zykrah/firmware-scripts/files/15056289/priya50.13.json)

You'll need to rename the following netlist to "trinity.net"
[trinity.txt](https://github.com/zykrah/firmware-scripts/files/15056283/trinity.txt)

**Comment by zykrah** [comment]
Unfortunately that's just a limitation of how QMK works. Complex multilayouts require more nuance and usually that involves a human configuring it in the way they desire. QMK doesn't actually officially support "multilayout" (i.e. the version that you use for VIA/VIAL). Their version of "multilayout" is a more vanilla QMK approach where all possible macros are defined separately in different "community layouts". 

As you mentioned, the only "fix" to this is to create at least one multilayout on the script that has all the possible keys in it. It doesn't have to be the 0th index, the script will automatically pick the layout index with the most configured keys in it, so you can put it at as the last index if you wish. You can also alternatively create ghost keys (the decal option on KLE) which will hide keys from the layout on VIA/L when loaded.

It's difficult to address this problem when you start adding a ton of multilayouts, I have tried in the past but unfortunately i would say the end user has to determine how they want to use the script to achieve desired results and/or manually modify code as per a "normal QMK workflow", because QMK and VIA/L don't line up nicely and its hard to write a script that can output both data types from the same one KLE without something breaking. Too many different ways to approach multilayout with little official support/guidance (at least for really complex multilayouts) means it's hard to autotmate it.

I've done my best to address the typical multialyout cases (e.g. examples on the docs) but anything beyond that i cannot guarantee the script will work. At best I can add a check for these kinds of issues in the script with an error message that links to some documentation with some more explanation.

**Comment by luis-godinez** [comment]
Thanks for the prompt reply. The script is amazing and has definitely streamlined by pcb workflow.

Adding a note to the documentation would be helpful!
